Repository samuel-gamelin/Rabbits-and-Foxes, pull requests merged in 2020-05, with the labels that each got.

#60 Hint Update
  src/main/java/model/Fox.java
  src/main/java/ui/GameView.java
  src/main/java/ui/MainMenu.java
Labels: enhancement

#61 Use Lombok to remove boilerplate code
  pom.xml
  src/main/java/controller/GameController.java
  src/main/java/model/Board.java
  src/main/java/model/BoardListener.java
  src/main/java/model/Fox.java
  src/main/java/model/MovablePiece.java
  src/main/java/model/Mushroom.java
  src/main/java/model/Piece.java
  src/main/java/model/Rabbit.java
  src/main/java/model/Tile.java
  src/main/java/resources/Resources.java
  src/main/java/ui/GUIUtilities.java
  src/main/java/ui/GameView.java
  src/main/java/ui/LevelBuilder.java
  src/main/java/ui/LevelSelector.java
  src/main/java/ui/MainMenu.java
  src/main/java/util/Move.java
  src/main/java/util/Node.java
  src/main/java/util/Solver.java
  src/test/java/model/BoardTest.java
  src/test/java/model/FoxTest.java
  src/test/java/model/MushroomTest.java
  src/test/java/model/RabbitTest.java
  src/test/java/model/TileTest.java
  src/test/java/ui/GameViewTest.java
  src/test/java/util/MoveTest.java
  src/test/java/util/SolverTest.java
Labels: enhancement

#63 Update README.md
  README.md
Labels: documentation

#66 Update README.md
  README.md
Labels: documentation, enhancement
